version: '3'

services:

  app:
    build: .
    ports:
      - 80:8000
    command: ./run_web.sh
    depends_on:
      - redis
    networks:
      - my-bridge

  worker:
    build: .
    command: ./run_celery.sh
    depends_on:
      - redis
    networks:
      - my-bridge

  beat:
    build: .
    command: ./run_beat.sh
    depends_on:
      - redis
    networks:
      - my-bridge

  redis:
    image: redis
    networks:
      - my-bridge


networks:
  my-bridge:
    driver: bridge